version: "3.8"
services:
  emulator:
    image: xenum/docker-android-x86-10.0
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - ANDROID_VERSION=10.0
        - API_LEVEL=29
        - IMG_TYPE=google_apis
        - CHROME_DRIVER=74.0.3729.6
        - SYS_IMG=x86
        - BROWSER=chrome
      cache_from:
        - xenum/docker-android-x86-10.0:latest
        - appium/appium:1.18.0-p0
    network_mode: bridge
    privileged: true
    ports:
      - "6080:6080"
      - "5554:5554"
      - "5555:5555"
      - "5900:5900"
    environment:
      - DEVICE=Samsung Galaxy S6
    container_name: android-container
