version: "3.8"
services:
  emulator:
    image: xenum/docker-android-x86-8.1
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - ANDROID_VERSION=8.1
        - API_LEVEL=27
        - IMG_TYPE=google_apis
        - CHROME_DRIVER=74.0.3729.6
        - SYS_IMG=x86
        - BROWSER=chrome
      cache_from:
        - xenum/docker-android-x86-8.1:latest
        - appium/appium:1.18.0-p0
    network_mode: bridge
    privileged: true
    ports:
      - "8200:8200"
    volumes:
      - "./ssh_keys:/root/.ssh"
    environment:
      - DEVICE=Nexus 5 
    container_name: android-container
