name: Lint

on:
  pull_request:
        branches: [master]
  push:
    branches-ignore: [master]

jobs:
  Lint:
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_AUTHOR_NAME: linter-action
        GIT_AUTHOR_EMAIL: linter@action.test
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: sudo gem install overcommit; curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.39.0/ktlint && chmod a+x ktlint
    - name: Lint ✨
      run: overcommit --sign; overcommit -r
