name: "Close stale issues"
on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked as stale and will be automatically closed in 7 days if there is no activity.'
        stale-pr-message: 'This PR has been marked as stale and will be automatically closed in 7 days if there is no activity.'
        close-issue-message: 'This issue has been automatically closed due to inactivity.'
        close-pr-message: 'This PR has been automatically closed due to inactivity.'
        days-before-stale: 14
        days-before-close: 7
        stale-pr-label: 'stale'
        stale-issue-label: 'stale'
        exempt-issue-labels: 'security,question,no-stale'
        exempt-pr-labels: 'security,question,no-stale'
